[package]
name = "sabre-ffi"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
stabby = "4.0"
mcrl2.workspace = true

[dev-dependencies]
test-log.workspace = true