[profile.release]
lto = true
incremental = true

[profile.bench]
debug = true

[workspace]
members = [
    "libraries/ldd-library/benchmarks", 
    "libraries/ldd-library/ldd",
    "libraries/*",
    "tools/*"
]

# Added these crates separatedly since the ldd-library has it's own workspace
exclude = [
    "libraries/ldd-library"
]