[profile.release]
lto = true
incremental = true

[profile.bench]
debug = true

[workspace]
members = [
    "libraries/mcrl2-rust",
    "libraries/ldd-library/benchmarks", # Add these crates separatedly since the ldd-library has it's own workspace
    "libraries/ldd-library/ldd",
    "tools/*"
]