[profile.release]
lto = "thin"

[profile.bench]
debug = "line-tables-only"

[workspace]
resolver = "2"
members = [
    "libraries/*",
    "tools/*"
]

[workspace.package]
authors = ["Maurice Laveaux"]
edition = "2021"
license = "BSL-1.0"
repository = "https://github.com/mlaveaux/mCRL2-rust.git"
rust-version = "1.70.0"
version = "0.1.0"

[workspace.dependencies]
rand = "0.8"
ahash = "0.8"
log = "0.4"
test-log = "0.2"
env_logger = "0.10"
clap = { version = "4.4", features = ["derive"] }

sabre = { path = "libraries/sabre" }
mcrl2 = { path = "libraries/mcrl2" }
mcrl2-macros = { path = "libraries/mcrl2-macros" }