[profile.release]
lto = true
incremental = true

[profile.bench]
debug = true

[workspace]
resolver = "2"
members = [
    "libraries/*",
    "tools/*"
]

[workspace.package]
version = "0.1.0"
rust-version = "1.70.0"
edition = "2021"

[workspace.dependencies]
rand = "0.8"
ahash = "0.8"
clap = { version = "4.4", features = ["derive"] }