[profile.release]
lto = "thin"

[profile.bench]
debug = "line-tables-only"

[workspace]
resolver = "2"
members = [
    "libraries/*",
    "libraries/sabre-compiling/sabre-compiled",
    "tools/*"
]

[workspace.package]
authors = ["Maurice Laveaux"]
edition = "2021"
license = "BSL-1.0"
repository = "https://github.com/mlaveaux/mCRL2-rust.git"
rust-version = "1.70.0"
version = "0.1.0"

[workspace.dependencies]
ahash = "0.8"
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rand = "0.8"
regex = "1.10"
test-log = "0.2"

# The workspace libraries.
sabre = { path = "libraries/sabre" }
mcrl2 = { path = "libraries/mcrl2" }
mcrl2-macros = { path = "libraries/mcrl2-macros" }