[package]
name = "mcrl2-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = { version = "1.0", features = ["parallel"] }
cc = "1.0"
cargo-emit = "0.2.1"