[package]
name = "lts"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
fxhash.workspace = true
bumpalo.workspace = true
log.workspace = true
rand.workspace = true

[dev-dependencies]
test-log.workspace = true