[package]
name = "ldd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1"
ahash = "0.8"
static_assertions = "1.1"
utilities = { path="../../libraries/utilities" }