[package]
name = "sabre"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
mcrl2 = { path="../../libraries/mcrl2" }
ahash.workspace = true
itertools = "0.12"
rand.workspace = true
rustc-hash = "1.1"
smallvec = "1.11"