[package]
name = "mcrl2-sys"
links = "mcrl2"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = { version = "1.0", features = ["parallel"] }
cc = "1.0"