[package]
name = "mcrl2-sys"
version = "0.1.0"
rust-version = "1.70"
edition = "2021"
links = "mcrl2"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = { version = "1.0", features = ["parallel"] }
cc = "1.0"