[package]
name = "rec-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
mcrl2-sys = { path="../mcrl2-sys" }
sabre = { path="../sabre" }
pest = "2.1.3"
pest_derive = "2.1.0"

[dev-dependencies]
test-case = "3.1.0"