[package]
name = "ltsgraph-lib"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
mcrl2rust-io.workspace = true
mcrl2rust-lts.workspace = true
mcrl2rust-unsafety.workspace = true

cosmic-text.workspace = true
glam.workspace = true
log.workspace = true
rand.workspace = true
tiny-skia.workspace = true