[package]
name = "ltsgraph-lib"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
cosmic-text.workspace = true
glam.workspace = true
tiny-skia.workspace = true
io.workspace = true
rand.workspace = true
log.workspace = true