[package]
name = "ltsgraph-lib"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
cosmic-text = "0.11"
glam = "0.26"
tiny-skia = "0.11"
io.workspace = true
rand.workspace = true