[package]
name = "mcrl2rewrite"
version = "0.1.0"
rust-version = "1.70"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
mcrl2 = { path = "../../libraries/mcrl2" }
rec-tests = { path = "../../libraries/rec-tests" }
sabre = { path = "../../libraries/sabre" }