[package]
name = "mcrl2rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
mcrl2-sys = { path="../../libraries/mcrl2-sys" }
rec-tests = { path="../../libraries/rec-tests" }
sabre = { path="../../libraries/sabre" }