[package]
name = "xtask"
version = "0.1.0"
rust-version = "1.70"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13"
fs_extra = "1.0"
glob = "0.3"