[package]
name = "mcrl2-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
ldd = { path="../ldd" }
mcrl2-sys = { path="../mcrl2-sys" }
rand = "0.8"
rec-tests = { path="../rec-tests" }
sabre = { path="../sabre" }
utilities = { path="../utilities" }

[[bench]]
name = "benchmarks"
harness = false