[package]
name = "mcrl2-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
mcrl2-rust = { path="../mcrl2-rust" }
rec-tests = { path="../rec-tests" }
rand = "0.8.4"
sabre = { path="../sabre" }
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "rewrite"
harness = false