[package]
name = "mcrl2-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
mcrl2-sys = { path="../mcrl2-sys" }
rec-tests = { path="../rec-tests" }
ldd = { path="../ldd" }
rand = "0.8"
sabre = { path="../sabre" }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "rewrite"
harness = false