[package]
name = "mcrl2"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
ahash.workspace = true
rand.workspace = true
log.workspace = true
test-log.workspace = true
mcrl2-sys = { path="../mcrl2-sys" }
utilities = { path="../utilities" }