[package]
name = "ltsgraph"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
leptos = { version = "0.6.5", features = ["csr"] }
clap.workspace = true
env_logger.workspace = true
io.workspace = true
console_error_panic_hook = "0.1.7"
