[package]
name = "ltsgraph"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
glam = "0.25"
slint = "1.4"
rfd = "0.13"
tiny-skia = "0.11"
clap.workspace = true
env_logger.workspace = true
log.workspace = true
io.workspace = true
mcrl2.workspace = true
rand.workspace = true

[build-dependencies]
slint-build = "1.4"