[package]
name = "utilities"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
once_cell.workspace = true
rand.workspace = true
crossbeam-utils.workspace = true