[package]
name = "utilities"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
crossbeam-utils.workspace = true
rand.workspace = true
test-log.workspace = true
log.workspace = true