[package]
name = "io"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
bitstream-io = "2.2"
thiserror = "1"
streaming-iterator = "0.1"
fxhash = "0.2"
regex.workspace = true