[package]
name = "sabre-compiled"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
abi_stable = "0.11"
sabre-compiling = { path = "../" }