[package]
name = "enumerate"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true
mcrl2.workspace = true
sabre.workspace = true