name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:    
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4
      
    - name: Install nextest
      uses: taiki-e/install-action@nextest
      
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run tests
      run: cargo nextest run -- --include-ignored
      env:
        RUST_BACKTRACE: full
        RUSTC_WRAPPER: sccache
