name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:    
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.3
      
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: llvm
        version: 1.0
      if: matrix.os == 'ubuntu-latest'

    - name: Install MacOS Dependencies
      run: |
        brew update
        brew install llvm    
      if: matrix.os == 'macos-latest'  

    - name: Install Nightly Rust
      run: rustup component add llvm-tools-preview

    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Run tests
      run: cargo +nightly xtask sanitizer
      env:
        RUST_BACKTRACE: full
        RUSTC_WRAPPER: sccache
